### ISSUE TITLE
What is the logic that defines Qi?

### ISSUE THREAD

**Issue by AlphaQi** [sciencefans/trojans-face-recognizer#5]
![1572350384(1)](https://user-images.githubusercontent.com/18130290/67765314-c9d12780-fa86-11e9-93f1-5bda11e34841.png)
In your paper, you defined Qi in the pic, 
in my mind, Qi is the Similarity of face image(person A) and it's registration photo(person A) Divide by the max Similarity of  face image(person A) between others registration photos(person B,C,D,E......), is my understanding correct?can you tell me the reason?

**Comment by songguanglu** [comment]
Your understanding is correct and the W_c is the centroid of each class (the weight of the classification layer in our experiments).
The similarity cos(F_I, W_c) can represent the intra-class distance and the max similarity of face image (person A) between other centroids can represent the inter-class distance. If one image has a small intra-class distance and large inter-class distance, we think it deserves a high quality score and Q_I can better formulate this idea.

**Comment by AlphaQi** [comment]
Thanks very much~
